# Generated by Django 3.2.12 on 2023-12-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20231225_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jackets',
            options={'verbose_name': 'Jacket', 'verbose_name_plural': 'Jackets'},
        ),
        migrations.AlterModelOptions(
            name='jeans',
            options={'verbose_name': 'Jeans', 'verbose_name_plural': 'Jeans'},
        ),
        migrations.AlterModelOptions(
            name='shirts',
            options={'verbose_name': 'Shirt', 'verbose_name_plural': 'Shirts'},
        ),
        migrations.AlterModelOptions(
            name='t_shirts',
            options={'verbose_name': 'T-shirt', 'verbose_name_plural': 'T-shirts'},
        ),
        migrations.AlterField(
            model_name='jackets',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jackets',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='jeans',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jeans',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='t_shirts',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='t_shirts',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
